CREATE DATABASE QuanLiSieuThiMini
USE QuanLiSieuThiMini

CREATE TABLE KhachHang (
	IDKhachHang VARCHAR(10) PRIMARY KEY,
	IDNhomKH VARCHAR(10),
	HoTen NVARCHAR(150),
	GioiTinh NVARCHAR(5),
	SoDienThoai CHAR(10),
	DiaChi NVARCHAR(MAX)
)
CREATE TABLE NhomKhachHang (
	IDNhomKH VARCHAR(10) PRIMARY KEY,
	TenNhom NVARCHAR(100),
	LoaiNhom INT
)
CREATE TABLE DonViTinh (
	IDDonViTinh VARCHAR(10) PRIMARY KEY,
	MacDinh VARCHAR(20)
)
CREATE TABLE DonViTinhKhac (
	ID VARCHAR(20) PRIMARY KEY,
	IDSanPham VARCHAR(10),
	IDDonViTinh VARCHAR(10)
)
CREATE TABLE NhanVien (
	IDNhanVien VARCHAR(10) PRIMARY KEY,
	IDBoPhan VARCHAR(10) ,
	HoTen NVARCHAR(150),
	GioiTinh NVARCHAR(5),
	SoDienThoai CHAR(10),
	DiaChi NVARCHAR(MAX),
	LoaiNhanVien INT
)
CREATE TABLE BoPhan (
	IDBoPhan VARCHAR(10) PRIMARY KEY,
	TenBoPhan NVARCHAR(50)
)
CREATE TABLE NhomSanPham (
	IDNhomSanPham VARCHAR(10) PRIMARY KEY,
	TenNhom NVARCHAR(100),
	LoaiNhom INT,
	IDKhuVuc VARCHAR(10)
)
CREATE TABLE SanPham (
	IDSanPham VARCHAR(10) PRIMARY KEY,
	IDNhomSanPham VARCHAR(10),
	TenSanPham VARCHAR(100),
	DonGia FLOAT,
	IDDonViTinh VARCHAR(10),
	NgaySanXuat DATE,
	HanSuDung DATE
)
CREATE TABLE Kho (
	STT INT PRIMARY KEY ,
	IDNhomSanPham VARCHAR(10),
	IDSanPham VARCHAR(10),
	NgayNhap DATE,
	NgayXuat DATE,
	SoLuong INT
)
CREATE TABLE HoaDon (
	IDHoaDon VARCHAR(10) PRIMARY KEY ,
	NgayTao DATETIME,
	SoLuong INT ,
	IDKhachHang VARCHAR(10),
	IDNhanVien VARCHAR(10),
	TongTien FLOAT ,
	TrangThai INT
)
CREATE TABLE DongHoaDon (
	IDDongHoaDon VARCHAR(10) PRIMARY KEY,
	IDHoaDon VARCHAR(10),
	IDSanPham VARCHAR(10),
	IDDonViTinh VARCHAR(10),
	IDNhanVien VARCHAR(10),
	SoLuong INT
)
CREATE TABLE KhuVuc (
	IDKhuVuc VARCHAR(10) PRIMARY KEY,
	TenKhuVuc NVARCHAR(100)
)